apiVersion: batch/v1
kind: CronJob
metadata:
  name: docker-test-batch
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: docker-test
            image: docker-example:0.0.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - echo hello docker-test-batch
            volumeMounts:
            - mountPath: /logs
              name: test-volume
          restartPolicy: OnFailure
          volumes:
          - name: test-volume
            hostPath:
              # directory location on host
              path: /var/lib/docker/volumes/logs/_data
              # this field is optional
              type: Directory