server:
  servlet:
    context-path: /docker-test
    session:
      timeout: 1800
    encoding:
      charset: UTF-8
      enabled: true
  tomcat:
    accesslog:
      directory: ${app.home}/logs
      enabled: true
      pattern: "%h %l %u %t \"%r\" %>s %b"
    max-connections: 1000
    min-spare-threads: 10
    max-threads: 10
  error:
    whitelabel:
      enabled: false
      
############################################################################
# Log properties
logging:
  file:
    name: ${app.home}/logs/test.log
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative][%thread] %-5level %logger{36} - %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative][%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"
      max-file-size: 10MB
      max-history: 7
 